version: 2
jobs:
  prepare:
    docker:
      - image: circleci/node:8
    working_directory: ~/danger-plugin-commit-lint
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/danger-plugin-commit-lint
          paths:
            - .

  test:
    docker:
      - image: circleci/node:8
    working_directory: ~/danger-plugin-commit-lint

    steps:
      - attach_workspace:
          at: ~/danger-plugin-commit-lint
      - run: yarn test

  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/danger-plugin-commit-lint
    steps:
      - attach_workspace:
          at: ~/danger-plugin-commit-lint
      - run: yarn build

  lint:
    docker:
      - image: circleci/node:8
    working_directory: ~/danger-plugin-commit-lint
    steps:
      - attach_workspace:
          at: ~/danger-plugin-commit-lint
      - run: yarn lint

workflows:
  version: 2
  workflow:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
      - build:
          requires:
            - prepare
      - lint:
          requires:
            - prepare